<?php
echo '<section id="icons" class="icons">'.PHP_EOL;
echo '<div class="container-fluid">'.PHP_EOL;
echo '<div class="row">'.PHP_EOL;
echo '<div class="icons__item col-6 col-md-3">'.PHP_EOL;
echo '<img class="icons__img" src="'.get_stylesheet_directory_uri().'/sprites/books.svg" alt="">'.PHP_EOL;
echo '<h3 class="icons__title">Education Services</h3>'.PHP_EOL;
echo '<p class="icons__desc">Kingster University was established by John Smith in 1920 for the public benefit and it is recognized.</p>'.PHP_EOL;
echo '<a class="icons__button">Learn More</a>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="icons__item col-6 col-md-3">'.PHP_EOL;
echo '<img class="icons__img" src="'.get_stylesheet_directory_uri().'/sprites/global.svg" alt="">'.PHP_EOL;
echo '<h3 class="icons__title">International Hubs</h3>'.PHP_EOL;
echo '<p class="icons__desc">Kingster University was established by John Smith in 1920 for the public benefit and it is recognized.</p>'.PHP_EOL;
echo '<a class="icons__button">Learn More</a>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="icons__item col-6 col-md-3">'.PHP_EOL;
echo '<img class="icons__img" src="'.get_stylesheet_directory_uri().'/sprites/diploma.svg" alt="">'.PHP_EOL;
echo '<h3 class="icons__title">Bachelor’s and Master’s</h3>'.PHP_EOL;
echo '<p class="icons__desc">Kingster University was established by John Smith in 1920 for the public benefit and it is recognized.</p>'.PHP_EOL;
echo '<a class="icons__button">Learn More</a>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="icons__item col-6 col-md-3">'.PHP_EOL;
echo '<img class="icons__img" src="'.get_stylesheet_directory_uri().'/sprites/institute.svg" alt="">'.PHP_EOL;
echo '<h3 class="icons__title">University Life</h3>'.PHP_EOL;
echo '<p class="icons__desc">Kingster University was established by John Smith in 1920 for the public benefit and it is recognized.</p>'.PHP_EOL;
echo '<a class="icons__button">Learn More</a>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</section>'.PHP_EOL;