<?php
echo '<section id="news" class="news">'.PHP_EOL;
echo '<div class="container-fluid">'.PHP_EOL;
echo '<div class="row">'.PHP_EOL;
echo '<div class="col-12 col-md-9">'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="col-12 col-md-3">'.PHP_EOL;
echo '<h3><img src="'.get_template_directory().'/sprites/link.svg" alt="" class="inline_icon">';
_e('Quick Links', 'bei_core');
echo '</h3>'.PHP_EOL;
echo '<ul>'.PHP_EOL;
echo '<li><a href="#">Alumni &amp; Donors</a></li>'.PHP_EOL;
echo '<li><a href="#">Athletic Calendar</a></li>'.PHP_EOL;
echo '<li><a href="#">All Kingster&apos;s Events</a></li>'.PHP_EOL;
echo '<li><a href="#">Partnership &amp; Out Reach</a></li>'.PHP_EOL;
echo '<li><a href="#">Academic Programs</a></li>'.PHP_EOL;
echo '<li><a href="#">Tution And Fees</a></li>'.PHP_EOL;
echo '</ul>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</section>'.PHP_EOL;
