<?php
echo '<section id="news" class="news">'.PHP_EOL;
echo '<div class="container-fluid">'.PHP_EOL;
echo '<div class="row">'.PHP_EOL;
echo '<div id="brief" class="brief col-12 col-md-9">'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div id="quick" class="quick col-12 col-md-3">'.PHP_EOL;
echo '<h3 class="quick__title"><img src="'.get_template_directory_uri().'/sprites/link.svg" alt="" class="inline_icon">';
_e('Quick Links', 'bei_core');
echo '</h3>'.PHP_EOL;
echo '<ul class="quick__list">'.PHP_EOL;
echo '<li class="quick__item"><a href="#" class="quick__link">Alumni &amp; Donors</a></li>'.PHP_EOL;
echo '<li class="quick__item"><a href="#" class="quick__link">Athletic Calendar</a></li>'.PHP_EOL;
echo '<li class="quick__item"><a href="#" class="quick__link">All Kingster&apos;s Events</a></li>'.PHP_EOL;
echo '<li class="quick__item"><a href="#" class="quick__link">Partnership &amp; Out Reach</a></li>'.PHP_EOL;
echo '<li class="quick__item"><a href="#" class="quick__link">Academic Programs</a></li>'.PHP_EOL;
echo '<li class="quick__item"><a href="#" class="quick__link">Tution And Fees</a></li>'.PHP_EOL;
echo '</ul>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</section>'.PHP_EOL;
