<?php
$gcwb_title       = get_sub_field('gcwb_title');
$gcwb_content     = get_sub_field('gcwb_content');
$gcwb_box_icon    = get_sub_field('gcwb_box_icon');
$gcwb_box_title   = get_sub_field('gcwb_box_title');
$gcwb_box_content = get_sub_field('gcwb_box_content');
echo '<section id="content" class="gencontent">'.PHP_EOL;
echo '<div class="content-fluid">'.PHP_EOL;
echo '<div class="row align-content-center gencontent__wrapper">'.PHP_EOL;
echo '<div class="col-12 col-md-10 gencontent__content">'.PHP_EOL;
echo '<span class="gencontent__title">'.$gcwb_title.'</span>'.PHP_EOL;
echo '<span class="gencontent__desc">'.$gcwb_content.'</span>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '<div class="row align-content-center gencontent__boxes">'.PHP_EOL;
echo '<div class="gencontent__boxes--item col-12 col-md-4">'.PHP_EOL;
echo '<span class="gencontent__boxes--icon">'.file_get_contents(get_stylesheet_directory_uri().'/sprites/'.$gcwb_box_icon.'.svg').'</span>'.PHP_EOL;
echo '<h4 class="gencontent__boxes--title">'.$gcwb_box_title.'</h4>'.PHP_EOL;
echo '<span class="gencontent__boxes--desc">'.$gcwb_box_content.'</span>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;
echo '</section>'.PHP_EOL;